{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "b3548444",
   "metadata": {},
   "outputs": [],
   "source": [
    "from __future__ import annotations\n",
    "import os\n",
    "import re\n",
    "import math\n",
    "import json\n",
    "import logging\n",
    "import sys\n",
    "from datetime import datetime\n",
    "from typing import Any, Dict, List, Literal, Optional, Tuple, TypedDict, Union\n",
    "\n",
    "import torch\n",
    "import requests\n",
    "from pydantic import ValidationError, BaseModel, Field\n",
    "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
    "from langgraph.graph import StateGraph, END\n",
    "from pypdf import PdfReader, PdfWriter\n",
    "from bs4 import BeautifulSoup"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "821b4949",
   "metadata": {},
   "outputs": [],
   "source": [
    "os.chdir('/Users/kimseungyeon1/Desktop/금융sllm/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "ab787399",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "로그 파일이 다음 경로에 생성됩니다: /Users/kimseungyeon1/Desktop/금융sllm/analysis_log_20260408_135551.log\n"
     ]
    }
   ],
   "source": [
    "#로그 파일 설정\n",
    "current_path = os.getcwd()\n",
    "log_filename = os.path.join(current_path, f\"analysis_log_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log\")\n",
    "print(f\"로그 파일이 다음 경로에 생성됩니다: {log_filename}\")\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format='%(asctime)s [%(levelname)s] %(message)s',\n",
    "    force=True, # 보고서 별로 로그 파일 따로 기록\n",
    "    handlers=[\n",
    "        logging.FileHandler(log_filename, encoding='utf-8'), # 파일 저장\n",
    "        logging.StreamHandler(sys.stdout)                  # 터미널 동시 출력\n",
    "    ]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "b4882752",
   "metadata": {},
   "outputs": [],
   "source": [
    "#래퍼 함수\n",
    "def print(*args, **kwargs):\n",
    "    logging.info(\" \".join(map(str, args)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "65646552",
   "metadata": {},
   "outputs": [],
   "source": [
    "#로컬 환경 변수 설정\n",
    "os.environ[\"HUGGINGFACEHUB_API_TOKEN\"] = \"\"\n",
    "os.environ[\"UPSTAGE_API_KEY\"] = \"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "9cd572c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Types / Schemas\n",
    "Unit = Literal[\"원\", \"천원\", \"백만원\", \"천만원\", \"억원\",\"UNKNOWN\"]\n",
    "CompareMode = Literal[\"QoQ\", \"YoY\",\"UNKNOWN\"] #분기 대비/전년동기 대비\n",
    "PeriodKey = str  # \"YYYYQn\"\n",
    "\n",
    "CANDIDATE_METRICS = [\n",
    "    \"영업이익(손실)\", \"법인세비용차감전순이익(손실)\",\"법인세비용(수익)\",\"당기순이익(손실)\",\n",
    "    \"영업수익\", \"매출액\", \"순이자이익\", \"수수료수익\",\n",
    "    \"매출원가\", \"매출총이익\", \"판매비와관리비\",\n",
    "    \"영업이익\",\n",
    "    \"법인세비용차감전순이익\", \"법인세비용\", \"당기순이익\", \"총포괄손익\",\n",
    "    \"지배기업소유주지분순이익\", \"비지배지분순이익\",\n",
    "    \"자산총계\", \"유동자산\", \"비유동자산\", \"유형자산\", \"무형자산\",\n",
    "    \"부채총계\", \"유동부채\", \"비유동부채\", \"차입금\",\n",
    "    \"자본총계\", \"지배기업소유주지분\", \"이익잉여금\",\n",
    "    \"영업활동현금흐름\", \"투자활동현금흐름\", \"재무활동현금흐름\",\n",
    "    \"수익(매출액)\", \"수익\", \"영업비용\", \"금융수익\", \"금융비용\",\n",
    "    \"기타수익\", \"기타비용\", \"기타포괄손익\"\n",
    "]\n",
    "\n",
    "#LLM이 기업 분석에 적합하다고 판단한 기업의 핵심 지표들\n",
    "class MetricSelectionOutput(BaseModel):\n",
    "    selected_metrics: List[str] = Field(description=\"제공된 보기 중 이 기업 분석에 가장 적합한 핵심 지표 5~10개\")\n",
    "\n",
    "#LLM이 추출한 보고서 기본 정보\n",
    "class LLMExtractionOutput(BaseModel):\n",
    "    unit_raw: str = Field(description=\"문서에 기록된 원본 단위\")\n",
    "    now_period: str = Field(description=\"당기 종료일 문자열\")\n",
    "    ref_period: str = Field(description=\"전기 종료일 문자열\")\n",
    "    now_period_key: str = Field(description=\"당기 PeriodKey (예: 2025Q1)\")\n",
    "    ref_period_key: str = Field(description=\"전기 PeriodKey (예: 2024Q1)\")\n",
    "\n",
    "    items: Dict[str, Dict[str, Union[str, int, float, None]]] = Field(\n",
    "        description=\"PeriodKey별 지표 데이터\"\n",
    "    )\n",
    "#단위 '백만원'으로 통일 후 시계열로 정렬한 데이터\n",
    "class NormalizedFinancials(BaseModel):\n",
    "    unit: Unit\n",
    "    periods: List[PeriodKey] \n",
    "    pl: Dict[str, List[float]]  \n",
    "\n",
    "#지표 변화 요약 (전년 또는 전분기 대비 증감과 증감률 계산 결과 저장)\n",
    "class TopMove(BaseModel):\n",
    "    metric: str\n",
    "    now_period: PeriodKey\n",
    "    ref_period: PeriodKey\n",
    "    now: float   #이번\n",
    "    ref: float   #비교\n",
    "    delta: float #변화량\n",
    "    delta_pct: Optional[float] = None  #변화율\n",
    "    flip_flag: bool = False  #흑자,적자 전환 여부\n",
    "\n",
    "#GrowthReasoningOutput에 보낼 내용 정리\n",
    "class GrowthReasoningInput(BaseModel):\n",
    "    unit: Unit   #화폐 단위\n",
    "    periods: List[PeriodKey]\n",
    "    metrics_timeseries: Dict[str, List[float]]  \n",
    "    top_moves: List[TopMove]\n",
    "    compare: CompareMode   #분기별/전년 동기 (QoQ/YoY)\n",
    "    now_period: PeriodKey\n",
    "    ref_period: Optional[PeriodKey]\n",
    "\n",
    "class GrowthReasoningOutput(BaseModel):\n",
    "    growth_trajectory: str\n",
    "    key_changes: List[str]\n",
    "    caveats: List[str]  \n",
    "    summary_table: Optional[str]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "7d03dcba",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 시간순 정렬\n",
    "def sort_period_keys(keys: List[PeriodKey]) -> List[PeriodKey]:\n",
    "    def kf(k: str) -> Tuple[int, int]:\n",
    "        m = re.match(r\"(\\d{4})Q([1-4])\", k)\n",
    "        return (int(m.group(1)), int(m.group(2))) if m else (0, 0) #정규화된 형식(YYYYQn) 아닌 경우 (0,0)반환\n",
    "    return sorted(keys, key=kf)\n",
    "\n",
    "#직전 분기를 reference period로 추출\n",
    "def pick_reference_index(periods: List[PeriodKey], idx_now: int, compare: CompareMode) -> Optional[int]:\n",
    "    if idx_now < 0 or idx_now >= len(periods):\n",
    "        return None\n",
    "    m = re.match(r\"(\\d{4})Q([1-4])\", periods[idx_now])\n",
    "    if not m:\n",
    "        return None\n",
    "    y, q = int(m.group(1)), int(m.group(2))\n",
    "    if compare == \"YoY\":\n",
    "        target = f\"{y-1}Q{q}\"\n",
    "    else:\n",
    "        target = f\"{y-1}Q4\" if q == 1 else f\"{y}Q{q-1}\"\n",
    "    try:\n",
    "        idx = periods.index(target)\n",
    "        return idx if idx < idx_now else None\n",
    "    except ValueError:\n",
    "        return None\n",
    "\n",
    "\n",
    "#단위 통일 (백만원 기준)\n",
    "def unit_multiplier_to_million(u: Unit) -> float:\n",
    "    mapping = {\"백만원\": 1.0, \"천원\": 1e-3, \"원\": 1e-6, \"천만원\": 10.0, \"억원\": 100.0}\n",
    "    return mapping.get(u, 1.0)\n",
    "\n",
    "#날짜 추출\n",
    "def get_quarter(month):\n",
    "    month = int(month)\n",
    "    if 1 <= month <= 3: return \"Q1\"\n",
    "    elif 4 <= month <= 6: return \"Q2\"\n",
    "    elif 7 <= month <= 9: return \"Q3\"\n",
    "    elif 10 <= month <= 12: return \"Q4\"\n",
    "    return \"\"\n",
    "\n",
    "# 날짜 추출 (최신 Upstage 통합 HTML 완벽 대응)\n",
    "def extract_financial_periods(doc_text_or_bundle):\n",
    "    if isinstance(doc_text_or_bundle, dict):\n",
    "        html_list = [t.get(\"html\", \"\") for t in doc_text_or_bundle.get(\"tables\", [])]\n",
    "        file_name = doc_text_or_bundle.get(\"file\", \"\")\n",
    "        clean_text = \" \".join([file_name] + html_list)\n",
    "    else:\n",
    "        clean_text = str(doc_text_or_bundle)\n",
    "\n",
    "    clean_text = clean_text.replace(\"\\\\n\", \" \").replace(\"\\\\t\", \" \").replace(\"&nbsp;\", \" \")\n",
    "    clean_text = re.sub(r'<[^>]+>', ' ', clean_text)  \n",
    "    clean_text = re.sub(r'\\s+', ' ', clean_text)      \n",
    "\n",
    "    pattern_full = r\"(제\\s*\\d+\\s*기\\s*(?:[1-4]분기|반기|사업연도)?\\s*)?(20\\d{2})\\s*[\\.년\\-\\/]\\s*(\\d{1,2})\\s*[\\.월\\-\\/]\\s*(\\d{1,2})\\s*[일\\.]?\\s*(?:부터|~|-|∼|—| )?\\s*(20\\d{2})\\s*[\\.년\\-\\/]\\s*(\\d{1,2})\\s*[\\.월\\-\\/]\\s*(\\d{1,2})\\s*[일\\.]?(?:\\s*까지)?\"\n",
    "    matches_full = re.findall(pattern_full, clean_text)\n",
    "\n",
    "    if matches_full:\n",
    "        extracted_dates = []\n",
    "        for match in matches_full:\n",
    "            term_str, start_y, start_m, start_d, end_y, end_m, end_d = match\n",
    "            clean_term = term_str.strip() if term_str else \"\"\n",
    "            end_date_str = f\"{end_y}.{int(end_m):02d}.{int(end_d):02d}\"\n",
    "            quarter = get_quarter(end_m)\n",
    "            period_key = f\"{end_y}{quarter}\"\n",
    "\n",
    "            # 중복 방지\n",
    "            if not any(d[0] == end_date_str for d in extracted_dates):\n",
    "                extracted_dates.append((end_date_str, period_key, clean_term))\n",
    "\n",
    "        # 내림차순 정렬 (최신 날짜가 맨 앞으로 오도록)\n",
    "        extracted_dates.sort(reverse=True, key=lambda x: x[0])\n",
    "\n",
    "        if len(extracted_dates) >= 2:\n",
    "            return extracted_dates[0][0], extracted_dates[0][1], extracted_dates[0][2], extracted_dates[1][0], extracted_dates[1][1], extracted_dates[1][2]\n",
    "        elif len(extracted_dates) == 1:\n",
    "            return extracted_dates[0][0], extracted_dates[0][1], extracted_dates[0][2], \"추출불가\", f\"{int(extracted_dates[0][1][:4])-1}{extracted_dates[0][1][4:]}\", \"전기\"\n",
    "#전체 보고서 중 포괄손익계산서 부분만 추출\n",
    "def auto_slice_financials(input_path, output_path):\n",
    "    reader = PdfReader(input_path)\n",
    "    writer = PdfWriter()\n",
    "    target_pages = []\n",
    "    print(f\"문서 스캔 중... (총 {len(reader.pages)}페이지)\")\n",
    "    metric_keywords = [\n",
    "        \"매출\", \"매출액\", \"영업수익\",\n",
    "        \"영업이익\", \"영업이익(손실)\",\n",
    "        \"당기순이익\", \"당기순이익(손실)\",\n",
    "        \"이자수익\", \"기타비용\", \"법인세비용\", \"법인세차감전순이익\",\n",
    "        \"기타포괄손익\", \"배당수익\", \"보험손익\", \"보험비용\", \"투자손익\"\n",
    "    ]\n",
    "    for i, page in enumerate(reader.pages):\n",
    "        text = page.extract_text()\n",
    "        if not text:\n",
    "            continue\n",
    "\n",
    "        clean_text = text.replace(\" \", \"\").replace(\"\\n\", \"\")\n",
    "\n",
    "        if \"포괄손익계산서\" in clean_text and \"연결\" not in clean_text:\n",
    "            hit_count = sum(1 for k in metric_keywords if k in clean_text)\n",
    "            if hit_count >= 2:\n",
    "                print(f\"(별도)포괄손익계산서 페이지 발견: {i}\")\n",
    "                target_pages.append(i)\n",
    "  \n",
    "    if not target_pages:\n",
    "        print(\"전체 페이지 사용\")\n",
    "        for i in range(len(reader.pages)):\n",
    "            writer.add_page(reader.pages[i])\n",
    "\n",
    "        with open(output_path, \"wb\") as f:\n",
    "            writer.write(f)\n",
    "        return output_path\n",
    "\n",
    "    # 첫 페이지 + 다음 페이지 추출 (표 최대 두 페이지에 작성된다고 생각)\n",
    "    first = target_pages[0]\n",
    "    pages = [first]\n",
    "    if first + 1 < len(reader.pages):\n",
    "        pages.append(first + 1)\n",
    "\n",
    "    for p in pages:\n",
    "        writer.add_page(reader.pages[p])\n",
    "\n",
    "    with open(output_path, \"wb\") as f:\n",
    "        writer.write(f)\n",
    "\n",
    "    print(f\"필터링 완료: {pages}\")\n",
    "    return output_path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "2805a877",
   "metadata": {},
   "outputs": [],
   "source": [
    "#table html/text를 bundle로 정리해서 LLM에 넘김\n",
    "class UpstageDocumentParseClient:\n",
    "    def __init__(self):\n",
    "        self.api_key = os.environ.get(\"UPSTAGE_API_KEY\")\n",
    "        if not self.api_key:\n",
    "            raise ValueError(\"UPSTAGE_API_KEY is required.\")\n",
    "        self.base_url = \"https://api.upstage.ai/v1/document-digitization\"\n",
    "\n",
    "    def parse(self, pdf_path: str, timeout: int = 600) -> Dict[str, Any]:\n",
    "        url = self.base_url\n",
    "        headers = {\"Authorization\": f\"Bearer {self.api_key}\"}\n",
    "\n",
    "        data = {\n",
    "            \"model\": \"document-parse-260128\",\n",
    "            \"ocr\": \"auto\",\n",
    "            \"chart_recognition\": \"true\",  # requests 폼 전송을 위해 문자열로 처리\n",
    "            \"coordinates\": \"true\",\n",
    "            \"output_formats\": '[\"html\"]',\n",
    "            \"base64_encoding\": '[\"figure\"]',\n",
    "        }\n",
    "\n",
    "        with open(pdf_path, \"rb\") as f:\n",
    "            files = {\"document\": f}\n",
    "            resp = requests.post(url, headers=headers, files=files, data=data, timeout=timeout)\n",
    "            resp.raise_for_status()\n",
    "            return resp.json()\n",
    "\n",
    "class LLMClient:\n",
    "    def __init__(self, model_id: str, use_cpu: bool=False):\n",
    "        self.device = \"cpu\" if use_cpu else (\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "        print(f\"{model_id} 로딩 중... device={self.device}\")\n",
    "        self.tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)\n",
    "        self.model = AutoModelForCausalLM.from_pretrained(\n",
    "            model_id,\n",
    "            torch_dtype=torch.bfloat16,\n",
    "            trust_remote_code=True\n",
    "        ).to(self.device)\n",
    "        self.model.eval()\n",
    "\n",
    "    def generate(self, system: str, user: str) -> str:\n",
    "        messages = [\n",
    "            {\"role\": \"system\", \"content\": system},\n",
    "            {\"role\": \"user\", \"content\": user}\n",
    "        ]\n",
    "\n",
    "        prompt = self.tokenizer.apply_chat_template(\n",
    "            messages,\n",
    "            tokenize=False,\n",
    "            add_generation_prompt=True\n",
    "        )\n",
    "\n",
    "        inputs = self.tokenizer(prompt, return_tensors=\"pt\").to(self.model.device)\n",
    "\n",
    "        with torch.no_grad():\n",
    "            outputs = self.model.generate(\n",
    "                **inputs,\n",
    "                max_new_tokens=1024,\n",
    "                do_sample=False,\n",
    "                repetition_penalty=1.15,\n",
    "                pad_token_id=self.tokenizer.eos_token_id,\n",
    "                eos_token_id=self.tokenizer.eos_token_id\n",
    "            )\n",
    "\n",
    "        input_length = inputs[\"input_ids\"].shape[1]\n",
    "        generated_tokens = outputs[0][input_length:]\n",
    "        content = self.tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()\n",
    "\n",
    "        # 모델이 혼자 사용자(<|user|>) 흉내를 내면 그 앞까지만 사용\n",
    "        if \"<|user|>\" in content:\n",
    "            content = content.split(\"<|user|>\")[0].strip()\n",
    "        if \"<|assistant|>\" in content:\n",
    "            content = content.split(\"<|assistant|>\")[0].strip()\n",
    "\n",
    "        content = content.replace(\"```json\", \"\").replace(\"```\", \"\").strip()\n",
    "\n",
    "        # 최종적으로 순수 JSON 괄호 { } 안의 내용만 추출\n",
    "        start = content.find('{')\n",
    "        end = content.rfind('}') + 1\n",
    "\n",
    "        return content[start:end] if start != -1 and end > start else content\n",
    "\n",
    "#LLM Table Extractor (HTML 파싱 없이 LLM로 표 읽기)\n",
    "class MetricSelector:\n",
    "    \"\"\"Pass 1: 문서를 보고 분석할 핵심 지표 풀을 확정합니다.\"\"\"\n",
    "    def __init__(self, llm: LLMClient):\n",
    "        self.llm = llm\n",
    "\n",
    "    def run(self, doc_bundle: Dict[str, Any], candidates: List[str]) -> List[str]:\n",
    "        # MetricSelectionOutput에서 지정한 형태로 답하도록 요청\n",
    "        # raw = '{\"selected_metrics\": [\"매출\", \"이익\"]}' 이런 식으로 답하게 됨\n",
    "        schema = MetricSelectionOutput.model_json_schema()\n",
    "        system = (\n",
    "            \"너는 10년차 재무 분석 전문가야.\\n\"\n",
    "            f\"제공된 문서를 분석하여, 기업의 재무 건전성과 성장성을 가장 잘 보여주는 핵심 지표를 최소 5개 선정해.\\n\"\n",
    "            \"단, 아래의 조건을 엄격히 준수할 것:\\n\"\n",
    "            \"1. '포괄손익계산서'에 적혀있는 지표명 그대로 추출해. 괄호 있는 경우 괄호 안 글자까지 그대로 추출해.\\n\"\n",
    "            \"2. '포괄손익계산서'에 적힌 텍스트와 100% 일치하는 지표이면서, 동시에 다음 [후보 지표 목록]에 포함된 지표만 선택할 것.\\n\"\n",
    "            f\"  [후보 지표 목록]: {candidates}\\n\"\n",
    "            \"3. 출력은 반드시 제공된 스키마와 일치하는 JSON 형태여야 하며, JSON 내부에 '//' 형태의 주석이나 부가 설명은 절대 포함하지 말 것.\\n\"\n",
    "        )\n",
    "        user = (\n",
    "            f\"DOCUMENT_BUNDLE:\\n{json.dumps(doc_bundle, ensure_ascii=False, indent=2)}\\n\\n\"\n",
    "            f\"SCHEMA:\\n{json.dumps(schema, ensure_ascii=False)}\"\n",
    "        )\n",
    "        raw = self.llm.generate(system=system, user=user)\n",
    "        return MetricSelectionOutput(**json.loads(raw)).selected_metrics\n",
    "\n",
    "\n",
    "class LLMTableExtractor:\n",
    "    \"\"\"Pass 2: Pass 1에서 확정된 지표에 대해서만 값을 추출합니다.\"\"\"\n",
    "    def __init__(self, llm: LLMClient):\n",
    "        self.llm = llm\n",
    "\n",
    "    def run(\n",
    "        self,\n",
    "        doc_bundle: Dict[str, Any],\n",
    "        compare: CompareMode,\n",
    "        selected_metrics: List[str]\n",
    "    ) -> LLMExtractionOutput:\n",
    "        schema = LLMExtractionOutput.model_json_schema()\n",
    "        now_date, now_key, now_term, ref_date, ref_key, ref_term = extract_financial_periods(doc_bundle)\n",
    "\n",
    "        system = f\"\"\"\n",
    "너는 제공된 문서에서 재무제표 핵심 수치만 선별해 정확한 수치를 추출하는 수석 재무 분석가다.\n",
    "\n",
    "[분석 대상 기간]\n",
    "아래 4개의 Key는 반드시 아래 지정해준 값으로 JSON에 넣어.\n",
    "- \"now_period_key\": \"{now_key}\"\n",
    "- \"now_period\": \"{now_date}\" (※ 표에서 데이터를 찾을 때 참고할 열 이름표: \"{now_term}\")\n",
    "- \"ref_period_key\": \"{ref_key}\"\n",
    "- \"ref_period\": \"{ref_date}\" (※ 표에서 데이터를 찾을 때 참고할 열 이름표: \"{ref_term}\")\n",
    "\n",
    "[목표]\n",
    "- 탐색 범위: 제공된 데이터의 `texts`(일반 텍스트 영역)와 `tables`(표 영역) 두 곳을 모두 탐색해라.\n",
    "- 추출 대상: 위 두 영역을 종합하여 '문서에 기록된 원본 단위(unit_raw)', '당기기간 및 데이터', '비교기간 및 데이터'를 찾아 추출해라.\n",
    "- 결과를 반드시 제공된 스키마와 일치하는 JSON으로만 출력해라.\n",
    "\n",
    "[데이터 추출 절대 원칙: 원본 100% 일치]\n",
    "1. 지표명(Key): 반드시 문서에 적힌 글자 그대로 출력해.\n",
    "2. 수치(Value): 단 한 글자도 바꾸지 말고 표에 보이는 그대로 복사해서 출력해.\n",
    "\n",
    "[지표명 복사 예시 (형식 변형 절대 금지)]\n",
    "- 괄호() 없는 원본: 영업이익 (O) / 영업이익(손실) (X)\n",
    "- 괄호() 있는 원본: 금융수익(손실) (O) / 금융수익 (X)\n",
    "\n",
    "[수치 복사 예시 (형식 변형 절대 금지)]\n",
    "- 쉼표(,) 유지: 489,341,873 (O) / 489341873 (X)\n",
    "- 괄호() 없는 원본: 1234 (O) / (1234) (X)\n",
    "- 괄호() 있는 원본: (1470) (O) / 1470 (X)\n",
    "\n",
    "[값 추출 규칙]\n",
    "1. 반드시 {selected_metrics}에 포함된 지표들만 추출해.\n",
    "3. 당기({now_term}) 데이터는 지표명 우측에 있는 **첫 번째 숫자**('3개월' 열)를 추출해.\n",
    "4. 전기({ref_term}) 데이터는 지표명 우측에 있는 **세 번째 숫자**('3개월' 열)를 추출해.\n",
    "5. 'items' 딕셔너리의 최상위 Key는 반드시 위에서 만든 PeriodKey여야 해.\n",
    "6. 모든 수치 값은 반드시 문자열로 출력해. 숫자형으로 출력하지 마.\n",
    "7. 모든 수치 반드시 맨 끝자리까지 정확하게 출력해.\n",
    "\n",
    "[자체 검증 - 반드시 수행]\n",
    "- 최종 출력은 반드시 스키마와 일치하는 JSON만 출력하라.\n",
    "\"\"\"\n",
    "        user = (\n",
    "            f\"DOCUMENT_BUNDLE:\\n{json.dumps(doc_bundle, ensure_ascii=False, indent=2)}\\n\\n\"\n",
    "            f\"SCHEMA:\\n{json.dumps(schema, ensure_ascii=False)}\\n\"\n",
    "            f\"COMPARE_HINT: {compare}\"\n",
    "        )\n",
    "        raw = self.llm.generate(system=system, user=user)\n",
    "\n",
    "        return LLMExtractionOutput(**json.loads(raw))\n",
    "\n",
    "class GrowthReasoner:\n",
    "    def __init__(self, llm): \n",
    "        self.llm = llm\n",
    "\n",
    "    def run(self, inp) -> GrowthReasoningOutput: \n",
    "        now_p = inp.now_period\n",
    "        ref_p = inp.ref_period\n",
    "        unit = inp.unit\n",
    "\n",
    "        table_rows = [f\"| 지표 | {ref_p} ({unit}) | {now_p} ({unit}) | 변동액 ({unit}) | 증감률 (%) |\", \"|---|---|---|---|---|\"]\n",
    "        analysis_hints = []\n",
    "\n",
    "        for m in inp.top_moves:\n",
    "            pct_str = f\"{m.delta_pct*100:.1f}%\" if m.delta_pct is not None else \"n/a\"\n",
    "            table_rows.append(f\"| {m.metric} | {m.ref:,.2f} | {m.now:,.2f} | {m.delta:,.2f} | {pct_str} |\")\n",
    "\n",
    "            status = \"흑자전환\" if m.flip_flag and m.now > 0 else (\"적자/악화\" if m.delta < 0 else \"성장/개선\")\n",
    "            analysis_hints.append(f\"- {m.metric}: {m.ref:,.0f} -> {m.now:,.0f} (변동: {m.delta:,.0f}, {pct_str}) [{status}]\")\n",
    "\n",
    "        perfect_markdown_table = \"\\n\".join(table_rows)\n",
    "\n",
    "\n",
    "        system = (\n",
    "            \"너는 기업 실적을 분석하는 10년차 재무 분석 전문가야. 모든 답변은 한국어로 작성해.\\n\"\n",
    "            \"제공된 문서를 바탕으로 아래 양식에 맞춰서 텍스트로만 답변해. 절대 JSON 형식({ })이나 표를 쓰지 마.\\n\\n\"\n",
    "            \"[제약 조건]\\n\"\n",
    "            \"1. 반드시 '포괄손익계산서'에 있는 5개의 지표에 대해서만 작성해. 문서에 없는 지표명 사용 금지.\\n\"\n",
    "            \"2. 중복된 내용 반복 출력 금지.\\n\\n\"\n",
    "            \"[총평]\\n\"\n",
    "            \"(기업의 실적 변동에 대한 총평을 금융 전문가 말투로 작성)\\n\\n\"\n",
    "            \"[지표분석]\\n\"\n",
    "            \"지표명 출력: 괄호와 괄호 안의 글자는 무조건 삭제하고 출력해. (예: '영업이익(손실)' -> '영업이익')\\n\"\n",
    "            \"분석 내용 작성 시 괄호 안 글자는 고려하지 말고 분석. (예: '영업이익(손실)' -> '영업이익'으로 생각하고 분석)\\n\"\n",
    "            \"분석 시 퍼센트 언급 가능. 금액 언급 금지.\\n\"\n",
    "            \"제공된 지표 모두에 대해 아래와 같은 리스트 형식으로 금융 전문가 말투의 분석 요약 작성\\n\"\n",
    "            \"- [해당 지표명]: (분석 내용 서술형으로 작성)\\n\"\n",
    "            \"\\n[특이사항]\\n\"\n",
    "            \"- (모든 지표 고려하여 우려되는 점이나 모니터링이 필요한 점을 금융전문가 말투로 작성. 단, 추측 금지, 오직 사실에 근거해 작성.)\"\n",
    "        )\n",
    "\n",
    "        user_content = f\"실적 데이터:\\n\" + \"\\n\".join(analysis_hints)\n",
    "        raw = self.llm.generate(system=system, user=user_content)\n",
    "\n",
    "\n",
    "        try:\n",
    "            raw_text = raw.strip()\n",
    "            if \"```\" in raw_text:\n",
    "                raw_text = re.sub(r'```[a-zA-Z]*\\n', '', raw_text)\n",
    "                raw_text = raw_text.replace('```', '').strip()\n",
    "\n",
    "            # [총평] 파싱\n",
    "            growth_traj = \"분석 요약 생성 실패\"\n",
    "            if \"[총평]\" in raw_text:\n",
    "                traj_match = re.split(r'\\[지표분석\\]|\\[특이사항\\]', raw_text.split(\"[총평]\")[1])[0]\n",
    "                growth_traj = traj_match.strip()\n",
    "\n",
    "            # [지표분석] 파싱\n",
    "            analysis_list = []\n",
    "            if \"[지표분석]\" in raw_text:\n",
    "                ana_match = re.split(r'\\[특이사항\\]|\\[총평\\]', raw_text.split(\"[지표분석]\")[1])[0]\n",
    "                lines = ana_match.strip().split('\\n')\n",
    "                analysis_list = [line.strip().lstrip('-').lstrip('*').strip() for line in lines if line.strip()]\n",
    "\n",
    "            if not analysis_list:\n",
    "                analysis_list = [f\"{h} 변동이 확인되었습니다.\" for h in analysis_hints]\n",
    "\n",
    "            # [특이사항] 파싱\n",
    "            caveats = []\n",
    "            if \"[특이사항]\" in raw_text:\n",
    "                cav_match = re.split(r'\\[총평\\]|\\[지표분석\\]', raw_text.split(\"[특이사항]\")[1])[0]\n",
    "                lines = cav_match.strip().split('\\n')\n",
    "                caveats = [line.strip().lstrip('-').lstrip('*').strip() for line in lines if line.strip()]\n",
    "\n",
    "            return GrowthReasoningOutput(\n",
    "                growth_trajectory=growth_traj,\n",
    "                key_changes=analysis_list,\n",
    "                kpi_summary=[], \n",
    "                summary_table=perfect_markdown_table,\n",
    "                caveats=caveats\n",
    "            )\n",
    "\n",
    "        except Exception as e:\n",
    "            print(f\"[GrowthReasoner] 텍스트 파싱 에러 발생: {e}\")\n",
    "            return GrowthReasoningOutput(\n",
    "                growth_trajectory=\"AI 분석 텍스트 파싱에 실패하여 수치 요약만 제공합니다.\",\n",
    "                key_changes=[f\"{h} 변동이 확인됩니다.\" for h in analysis_hints],\n",
    "                kpi_summary=[],\n",
    "                summary_table=perfect_markdown_table,\n",
    "                caveats=[\"AI 응답 형식이 깨져 원본 수치로 대체되었습니다.\"]\n",
    "            )\n",
    "\n",
    "#LangGraph \n",
    "class FGState(TypedDict, total=False):\n",
    "    pdf_paths: List[str]\n",
    "    compare: CompareMode\n",
    "    top_k: int\n",
    "\n",
    "    doc_bundle_by_pdf: Dict[str, Dict[str, Any]]\n",
    "    selected_metrics: List[str]  # Pass 1 결과물\n",
    "    llm_extraction_by_pdf: Dict[str, LLMExtractionOutput]\n",
    "\n",
    "    fin: NormalizedFinancials\n",
    "    now_period: PeriodKey\n",
    "    ref_period: Optional[PeriodKey]\n",
    "    ref_found: bool\n",
    "    top_moves: List[TopMove]\n",
    "    llm_reasoning: Optional[GrowthReasoningOutput]\n",
    "    warnings: List[str]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "a15ec812",
   "metadata": {},
   "outputs": [],
   "source": [
    "from bs4 import BeautifulSoup\n",
    "\n",
    "def node_upstage_parse(state: FGState, upstage: UpstageDocumentParseClient) -> FGState:\n",
    "    warnings = list(state.get(\"warnings\") or [])\n",
    "    doc_bundle_by_pdf = {}\n",
    "\n",
    "    for path in state[\"pdf_paths\"]:\n",
    "        try:\n",
    "            doc = upstage.parse(path)\n",
    "            elements = doc.get(\"elements\") or []\n",
    "\n",
    "            all_htmls = []\n",
    "            all_texts = []  # 표 외의 모든 텍스트 정보를 담을 바구니\n",
    "\n",
    "            for i, el in enumerate(elements):\n",
    "                content = el.get(\"content\", {})\n",
    "                category = el.get(\"category\", \"\") # 요소의 종류 (text, table, heading 등)\n",
    "\n",
    "                # 표(table)인 경우: HTML 정제 후 저장\n",
    "                if \"html\" in content:\n",
    "                    raw_html = content[\"html\"]\n",
    "                    soup = BeautifulSoup(raw_html, \"html.parser\")\n",
    "\n",
    "                    # '누적' 열 삭제 로직 \n",
    "                    for tr in soup.find_all(\"tr\"):\n",
    "                        cells = tr.find_all([\"td\", \"th\"])\n",
    "                        if len(cells) >= 5:\n",
    "                            cells[4].extract()\n",
    "                            cells[2].extract()\n",
    "                        elif len(cells) == 4:\n",
    "                            text_check = cells[1].get_text(strip=True)\n",
    "                            if \"누적\" in text_check:\n",
    "                                cells[3].extract()\n",
    "                                cells[1].extract()\n",
    "\n",
    "                    safe_html = str(soup)\n",
    "                    # 모든 표를 저장하되, 너무 길면 자름\n",
    "                    all_htmls.append({\"html\": safe_html.strip()[:12000]})\n",
    "\n",
    "                # 표가 아닌 모든 텍스트 요소(text, heading, caption 등) 수집\n",
    "                elif \"text\" in content:\n",
    "                    all_texts.append(content[\"text\"].strip())\n",
    "\n",
    "            # 수집된 모든 데이터를 번들에 담기\n",
    "            doc_bundle_by_pdf[path] = {\n",
    "                \"file\": os.path.basename(path),\n",
    "                \"texts\": all_texts,  \n",
    "                \"tables\": all_htmls\n",
    "            }\n",
    "\n",
    "        except Exception as e:\n",
    "            warnings.append(f\"[{os.path.basename(path)}] Upstage 실패: {e}\")\n",
    "\n",
    "    return {**state, \"doc_bundle_by_pdf\": doc_bundle_by_pdf, \"warnings\": warnings}\n",
    "\n",
    "def node_select_metrics(state: FGState, selector: MetricSelector) -> FGState:\n",
    "    \"\"\"Pass 1: 첫 번째 PDF(최신)를 기준으로 핵심 지표를 선택합니다.\"\"\"\n",
    "    bundles = list(state[\"doc_bundle_by_pdf\"].values())\n",
    "    if not bundles:\n",
    "      print(\"\\n[Upstage 파싱 실패 상세 원인]\")\n",
    "      print(state.get(\"warnings\"))\n",
    "      raise ValueError(\"문서 번들이 없습니다.\")\n",
    "\n",
    "    selected_metrics = selector.run(bundles[0], CANDIDATE_METRICS)\n",
    "    return {**state, \"selected_metrics\": selected_metrics}\n",
    "\n",
    "\n",
    "def node_llm_extract(state: FGState, extractor: LLMTableExtractor) -> FGState:\n",
    "    \"\"\"Pass 2: 선택된 지표만 모든 PDF에서 추출합니다.\"\"\"\n",
    "    warnings = list(state.get(\"warnings\") or [])\n",
    "    llm_extraction_by_pdf = {}\n",
    "    for path, bundle in state[\"doc_bundle_by_pdf\"].items():\n",
    "        try:\n",
    "            llm_extraction_by_pdf[path] = extractor.run(bundle, state[\"compare\"], state[\"selected_metrics\"])\n",
    "        except Exception as e:\n",
    "            warnings.append(f\"[{os.path.basename(path)}] LLM 추출 실패: {e}\")\n",
    "    return {**state, \"llm_extraction_by_pdf\": llm_extraction_by_pdf, \"warnings\": warnings}\n",
    "\n",
    "def node_merge_and_normalize(state: FGState) -> FGState:\n",
    "    warnings = list(state.get(\"warnings\") or [])\n",
    "    merged_data: Dict[PeriodKey, Dict[str, float]] = {}\n",
    "    unit_raw = \"UNKNOWN\"\n",
    "\n",
    "    # 메타 정보 수집\n",
    "    for _, ext in state[\"llm_extraction_by_pdf\"].items():\n",
    "        if unit_raw == \"UNKNOWN\" and ext.unit_raw != \"UNKNOWN\":\n",
    "            unit_raw = ext.unit_raw\n",
    "\n",
    "    unit_raw = str(unit_raw).strip().replace(\"(\", \"\").replace(\")\", \"\").replace(\"단위\", \"\").replace(\":\", \"\").replace(\" \", \"\")\n",
    "    scale = unit_multiplier_to_million(unit_raw)\n",
    "\n",
    "    allowed_metrics = {m.strip() for m in state[\"selected_metrics\"]}\n",
    "\n",
    "    # 기간별 지표 병합\n",
    "    for path, ext in state[\"llm_extraction_by_pdf\"].items():\n",
    "        for pk, metrics_dict in ext.items.items():\n",
    "            if not re.match(r\"^\\d{4}Q[1-4]$\", pk):\n",
    "                continue\n",
    "\n",
    "            if pk not in merged_data:\n",
    "                merged_data[pk] = {}\n",
    "\n",
    "            for metric, value in metrics_dict.items():\n",
    "                if value is None:\n",
    "                    continue\n",
    "\n",
    "                try:\n",
    "                    clean_metric = metric.strip()\n",
    "\n",
    "                    # 선택된 지표만 유지 \n",
    "                    if clean_metric not in allowed_metrics:\n",
    "                        continue\n",
    "\n",
    "                    clean_val = str(value).strip()\n",
    "                    clean_val = clean_val.replace(\",\", \"\").replace(\" \",\"\")\n",
    "\n",
    "                    if not clean_val:\n",
    "                        continue\n",
    "\n",
    "                    # (100) -> -100\n",
    "                    if clean_val.startswith(\"(\") and clean_val.endswith(\")\"):\n",
    "                        clean_val = \"-\" + clean_val[1:-1]\n",
    "                    # △100 -> -100\n",
    "                    elif clean_val.startswith(\"△\"):\n",
    "                        clean_val = \"-\" + clean_val[1:]\n",
    "                    # 혹시 LLM이 -(100) 같이 줬을 경우\n",
    "                    elif clean_val.startswith(\"-(\") and clean_val.endswith(\")\"):\n",
    "                        clean_val = \"-\" + clean_val[2:-1]\n",
    "\n",
    "                    merged_data[pk][clean_metric] = float(clean_val) * scale\n",
    "\n",
    "                except Exception as e:\n",
    "                    warnings.append(\n",
    "                        f\"[{os.path.basename(path)}] 값 변환 실패: pk={pk}, metric={metric}, value={value}, err={repr(e)}\"\n",
    "                    )\n",
    "\n",
    "    periods = sort_period_keys(list(merged_data.keys()))\n",
    "\n",
    "    pl_series = {}\n",
    "    for m in state[\"selected_metrics\"]:\n",
    "        m_strip = m.strip()\n",
    "        pl_series[m_strip] = [\n",
    "            merged_data.get(pk, {}).get(m_strip, math.nan)\n",
    "            for pk in periods\n",
    "        ]\n",
    "\n",
    "    fin = NormalizedFinancials(\n",
    "        unit=\"백만원\",\n",
    "        periods=periods,\n",
    "        pl=pl_series,\n",
    "    )\n",
    "\n",
    "    return {**state, \"fin\": fin, \"warnings\": warnings}\n",
    "\n",
    "def node_compute_moves(state: FGState) -> FGState:\n",
    "    fin = state[\"fin\"]\n",
    "    warnings = list(state.get(\"warnings\") or [])\n",
    "\n",
    "    # 유효한 기간 데이터가 아예 없는 경우\n",
    "    if not fin.periods:\n",
    "        warnings.append(\"추출된 유효한 기간 데이터가 없습니다. (LLM의 형식 위반 또는 누적 데이터 오인 필터링)\")\n",
    "        return {\n",
    "            **state,\n",
    "            \"now_period\": \"UNKNOWN\",\n",
    "            \"ref_period\": None,\n",
    "            \"ref_found\": False,\n",
    "            \"top_moves\": [],\n",
    "            \"warnings\": warnings\n",
    "        }\n",
    "    now_idx = len(fin.periods) - 1\n",
    "    now_p = fin.periods[now_idx]\n",
    "    ref_idx = pick_reference_index(fin.periods, now_idx, state[\"compare\"])\n",
    "    ref_p = fin.periods[ref_idx] if ref_idx is not None else None\n",
    "\n",
    "    top_moves = []\n",
    "    if ref_idx is not None:\n",
    "        for metric, values in fin.pl.items():\n",
    "            now, ref = values[now_idx], values[ref_idx]\n",
    "            if math.isnan(now) or math.isnan(ref): continue\n",
    "            d = now - ref\n",
    "            pct = None if ref == 0 else d / ref\n",
    "            top_moves.append(TopMove(metric=metric, now_period=now_p, ref_period=ref_p, now=now, ref=ref, delta=d, delta_pct=pct, flip_flag=(now >= 0 > ref) or (ref >= 0 > now)))\n",
    "        top_moves.sort(key=lambda x: (abs(x.delta_pct or 0.0), abs(x.delta)), reverse=True)\n",
    "\n",
    "    return {**state, \"now_period\": now_p, \"ref_period\": ref_p, \"ref_found\": ref_idx is not None, \"top_moves\": top_moves[:state[\"top_k\"]]}\n",
    "\n",
    "\n",
    "def node_optional_reasoning(state: FGState, reasoner: Optional[GrowthReasoner]) -> FGState:\n",
    "    if not reasoner: return state\n",
    "    inp = GrowthReasoningInput(\n",
    "        unit=state[\"fin\"].unit,\n",
    "        periods=state[\"fin\"].periods, metrics_timeseries=state[\"fin\"].pl,\n",
    "        top_moves=state[\"top_moves\"], compare=state[\"compare\"], now_period=state[\"now_period\"], ref_period=state.get(\"ref_period\")\n",
    "    )\n",
    "    try:\n",
    "      return {**state, \"llm_reasoning\": reasoner.run(inp)}\n",
    "    except Exception as e:\n",
    "      warnings = list(state.get(\"warnings\") or [])\n",
    "      warnings.append(f\"Reasoning 실패: {e}\")\n",
    "      return {**state, \"llm_reasoning\": None}\n",
    "\n",
    "def render_report(state: dict) -> str:\n",
    "    fin = state[\"fin\"]\n",
    "    lines = [\n",
    "        f\"[단위]: {fin.unit}, [비교]: {state['compare']}\",\n",
    "        f\"[선택된 지표] {', '.join(state['selected_metrics'])}\"\n",
    "    ]\n",
    "    # 핵심 지표 변동 (Top Moves)\n",
    "    lines.append(\"\\n1) 핵심 지표 변동 (Top Moves)\")\n",
    "    if state.get(\"top_moves\"):\n",
    "        for m in state[\"top_moves\"]:\n",
    "            pct = f\"{m.delta_pct*100:.1f}%\" if m.delta_pct is not None else \"n/a\"\n",
    "            lines.append(f\"- {m.metric}: Δ {m.delta:,.0f} ({pct})\")\n",
    "    else:\n",
    "        lines.append(\"- 추출된 지표 변동 내역이 없습니다.\")\n",
    "\n",
    "    # 분석 요약\n",
    "    if state.get(\"llm_reasoning\"):\n",
    "        rr = state[\"llm_reasoning\"]\n",
    "        lines.append(\"\\n2) 분석 요약\")\n",
    "        lines.append(f\"- 총평: {rr.growth_trajectory}\")\n",
    "\n",
    "        # 파이썬이 완벽하게 생성한 표 삽입\n",
    "        if rr.summary_table:\n",
    "            lines.append(\"\\n[핵심 지표 변화 요약 표]\")\n",
    "            lines.append(rr.summary_table)\n",
    "            lines.append(\"\")\n",
    "\n",
    "        # LLM이 작성한 분석글 \n",
    "        if rr.key_changes:\n",
    "            for b in rr.key_changes:\n",
    "                lines.append(f\"  • {b}\")\n",
    "\n",
    "        # 주의사항\n",
    "        if rr.caveats:\n",
    "            lines.append(\"\")\n",
    "            lines.append(\"- 특이사항/주의:\")\n",
    "            for c in rr.caveats:\n",
    "                lines.append(f\"  • {c}\")\n",
    "\n",
    "    if state.get(\"warnings\"):\n",
    "        lines.append(\"\\n[내부 경고/에러 로그]\")\n",
    "        for w in state[\"warnings\"]:\n",
    "            lines.append(f\"- {w}\")\n",
    "\n",
    "    return \"\\n\".join(lines)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "8df3228e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def build_graph(selector: MetricSelector, extractor: LLMTableExtractor, upstage: UpstageDocumentParseClient, reasoner: Optional[GrowthReasoner] = None):\n",
    "    g = StateGraph(FGState)\n",
    "    g.add_node(\"upstage_parse\", lambda s: node_upstage_parse(s, upstage))\n",
    "    g.add_node(\"select_metrics\", lambda s: node_select_metrics(s, selector))\n",
    "    g.add_node(\"llm_extract\", lambda s: node_llm_extract(s, extractor))\n",
    "    g.add_node(\"merge_normalize\", node_merge_and_normalize)\n",
    "    g.add_node(\"compute_moves\", node_compute_moves)\n",
    "    g.add_node(\"optional_reasoning\", lambda s: node_optional_reasoning(s, reasoner))\n",
    "\n",
    "    g.set_entry_point(\"upstage_parse\")\n",
    "    g.add_edge(\"upstage_parse\", \"select_metrics\")\n",
    "    g.add_edge(\"select_metrics\", \"llm_extract\")\n",
    "    g.add_edge(\"llm_extract\", \"merge_normalize\")\n",
    "    g.add_edge(\"merge_normalize\", \"compute_moves\")\n",
    "    g.add_edge(\"compute_moves\", \"optional_reasoning\")\n",
    "    g.add_edge(\"optional_reasoning\", END)\n",
    "    return g.compile()\n",
    "\n",
    "def run_pipeline(pdf_paths: List[str], llm: LLMClient, upstage: UpstageDocumentParseClient, compare: CompareMode = \"YoY\", top_k: int = 5, use_reasoning: bool = False):\n",
    "    app = build_graph(MetricSelector(llm), LLMTableExtractor(llm), upstage, GrowthReasoner(llm) if use_reasoning else None)\n",
    "    final_state = app.invoke({\"pdf_paths\": pdf_paths, \"compare\": compare, \"top_k\": top_k, \"warnings\": []})\n",
    "    return final_state, render_report(final_state)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d67c3b9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2026-04-07 22:36:28,636 [INFO] kakaocorp/kanana-1.5-2.1b-instruct-2505 로딩 중... device=cpu\n",
      "2026-04-07 22:36:31,601 [INFO] PDF 자동 분리를 시작합니다...\n",
      "2026-04-07 22:36:31,604 [INFO] 문서 스캔 중... (총 1페이지)\n",
      "2026-04-07 22:36:31,639 [INFO] 전체 페이지 사용\n",
      "2026-04-07 22:41:42,891 [INFO] \n",
      "[TableExtractor 원본 응답]\n",
      " {\n",
      "  \"unit_raw\": \"(단위 : 원)\",\n",
      "  \"now_period\": \"2025.09.30\",\n",
      "  \"ref_period\": \"2024.09.30\",\n",
      "  \"now_period_key\": \"2025Q3\",\n",
      "  \"ref_period_key\": \"2024Q3\",\n",
      "  \"items\": {\n",
      "    \"2025Q3\": {\n",
      "      \"영업이익(손실)\": \"640,113,803\",\n",
      "      \"법인세비용차감전순이익(손실)\": \"834,769,256\",\n",
      "      \"법인세비용(수익)\": \"23,555,974\",\n",
      "      \"당기순이익(손실)\": \"811,213,282\",\n",
      "      \"영업수익\": \"6,518,838,18 1\"\n",
      "    },\n",
      "    \"2024Q3\": {\n",
      "      \"영업이익(손실)\": \"1,028,285,54 5\",\n",
      "      \"법인세비용차감전순이익(손실)\": \"964,061,669\",\n",
      "      \"법인세비용(수익)\": \"21,051,790\",\n",
      "      \"당기순이익(손실)\": \"943,009,879\",\n",
      "      \"영업수익\": \"5,947,806,15 4\"\n",
      "    }\n",
      "  }\n",
      "} \n",
      "==================================================\n",
      "2026-04-07 22:43:14,164 [INFO] \n",
      "[LLM 추출 Raw Data]\n",
      "2026-04-07 22:43:14,168 [INFO] {\n",
      "  \"./temp_sliced_finance.pdf\": {\n",
      "    \"unit_raw\": \"(단위 : 원)\",\n",
      "    \"now_period\": \"2025.09.30\",\n",
      "    \"ref_period\": \"2024.09.30\",\n",
      "    \"now_period_key\": \"2025Q3\",\n",
      "    \"ref_period_key\": \"2024Q3\",\n",
      "    \"items\": {\n",
      "      \"2025Q3\": {\n",
      "        \"영업이익(손실)\": \"640,113,803\",\n",
      "        \"법인세비용차감전순이익(손실)\": \"834,769,256\",\n",
      "        \"법인세비용(수익)\": \"23,555,974\",\n",
      "        \"당기순이익(손실)\": \"811,213,282\",\n",
      "        \"영업수익\": \"6,518,838,18 1\"\n",
      "      },\n",
      "      \"2024Q3\": {\n",
      "        \"영업이익(손실)\": \"1,028,285,54 5\",\n",
      "        \"법인세비용차감전순이익(손실)\": \"964,061,669\",\n",
      "        \"법인세비용(수익)\": \"21,051,790\",\n",
      "        \"당기순이익(손실)\": \"943,009,879\",\n",
      "        \"영업수익\": \"5,947,806,15 4\"\n",
      "      }\n",
      "    }\n",
      "  }\n",
      "}\n",
      "2026-04-07 22:43:14,168 [INFO] \n",
      "============================================================\n",
      "2026-04-07 22:43:14,168 [INFO] \n",
      "[최종 생성된 분석 보고서]\n",
      "2026-04-07 22:43:14,169 [INFO] [단위]: 백만원, [비교]: YoY\n",
      "[선택된 지표] 영업이익(손실), 법인세비용차감전순이익(손실), 법인세비용(수익), 당기순이익(손실), 영업수익\n",
      "\n",
      "1) 핵심 지표 변동 (Top Moves)\n",
      "- 영업이익(손실): Δ -388 (-37.7%)\n",
      "- 당기순이익(손실): Δ -132 (-14.0%)\n",
      "- 법인세비용차감전순이익(손실): Δ -129 (-13.4%)\n",
      "- 법인세비용(수익): Δ 3 (11.9%)\n",
      "- 영업수익: Δ 571 (9.6%)\n",
      "\n",
      "2) 분석 요약\n",
      "- 총평: 최근 몇 개 분기의 실적에서 전반적으로 매출과 관련 수익성이 소폭 증가했으나, 주요 이익 지표들은 적자 또는 악화되는 경향을 보이고 있습니다. 특히 영업이익, 당기순이익, 법인세비용차감전순이익 등 핵심 손익 계정에서 적자가 확대되고 있어, 비용 구조나 원가 관리, 판매량 등의 변화가 실적 하락의 주원인일 것으로 판단됩니다. 다만, 법인세비용은 일시적인 요인으로 인해 소폭 증가한 것으로 보이며, 이는 세법 변경이나 외부 환경 변화에 따른 영향일 가능성이 높습니다.\n",
      "\n",
      "[핵심 지표 변화 요약 표]\n",
      "| 지표 | 2024Q3 (백만원) | 2025Q3 (백만원) | 변동액 (백만원) | 증감률 (%) |\n",
      "|---|---|---|---|---|\n",
      "| 영업이익(손실) | 1,028.29 | 640.11 | -388.17 | -37.7% |\n",
      "| 당기순이익(손실) | 943.01 | 811.21 | -131.80 | -14.0% |\n",
      "| 법인세비용차감전순이익(손실) | 964.06 | 834.77 | -129.29 | -13.4% |\n",
      "| 법인세비용(수익) | 21.05 | 23.56 | 2.50 | 11.9% |\n",
      "| 영업수익 | 5,947.81 | 6,518.84 | 571.03 | 9.6% |\n",
      "\n",
      "  • 영업이익: 최근 연속적으로 감소하며 적자 폭이 커지고 있습니다. 이는 제품 가격 하락, 원가 상승, 판매량 감소 등 다양한 내부 및 외적 요인이 복합적으로 작용한 결과로 보입니다. 향후에는 원가절감, 시장점유율 유지, 신제품 개발 등을 통해 실질적인 영업이익 개선을 위한 대책이 필요합니다.\n",
      "  • 당기순이익: 순이익도 유사하게 감소하고 있으며, 이는 법인세 부담 증가와 직접적으로 연결될 수 있으므로, 세무 구조 개선이나 비용 효율화가 동시에 이루어져야 합니다.\n",
      "  • 법인세비용차감전순이익: 역시 적자 상태이며, 이는 영업활동에서의 현금흐름 악화와 직결되어 있을 가능성이 큽니다. 자본적 투자, 연구개발비 등 성장 관련 지출이 과다하거나, 재무구조의 건전성 저하가 우려됩니다.\n",
      "  • 법인세비용: 일시적으로 증가하였으나, 장기적인 관점에서는 세법상 혜택 축소나 세무 리스크 관리 강화가 필요할 것으로 보입니다.\n",
      "  • 영업수익: 꾸준히 증가하고 있어 전체적인 매출 흐름은 긍정적임을 보여주지만, 이익률 개선 없이는 실질적인 수익 창출 효과가 제한적일 수 있습니다.\n",
      "- 특이사항/주의:\n",
      "  • 영업이익과 순이익의 지속적인 적자 확대는 비용 구조 개선, 원가경쟁력 강화, 매출처 다각화 등 구조적 문제 해결이 시급함을 의미합니다. 또한, 법인세비용 차감전순이익의 적자 폭이 크게 늘어나면서 재무구조의 취약성을 드러내고 있으므로, 자본확충이나 유동성 관리 방안도 함께 검토해야 할 것입니다. 단기적으로는 세법상 추가 혜택을 활용한 세무 리스크 완화가 중요하며, 장기적으로는 사업 포트폴리오 최적화와 수익성 중심의 경영 전략이 필수적입니다.\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    #upstage = UpstageDocumentParseClient()\n",
    "    #llm = LLMClient(model_id=\"kakaocorp/kanana-1.5-2.1b-instruct-2505\")\n",
    "    # 파일 경로 설정 \n",
    "    original_pdf = \"./폴라리스오피스:분기보고서:2025.11.14.pdf\"\n",
    "    sliced_pdf = \"./temp_sliced_finance.pdf\" # 잘라낸 파일 임시 저장\n",
    "\n",
    "    # 자동 스캔 및 자르기 실행\n",
    "    print(\"PDF 자동 분리를 시작합니다...\")\n",
    "    auto_slice_financials(original_pdf, sliced_pdf)\n",
    "\n",
    "    # 파이프라인 실행 \n",
    "    report_state, text = run_pipeline(\n",
    "        pdf_paths=[sliced_pdf], # 자른 파일을 투입\n",
    "        llm=llm,\n",
    "        upstage=upstage,\n",
    "        compare=\"YoY\",\n",
    "        top_k=5,\n",
    "        use_reasoning=True\n",
    "    )\n",
    "\n",
    "    # 결과 출력\n",
    "    print(\"\\n[LLM 추출 Raw Data]\")\n",
    "    print(json.dumps(report_state[\"llm_extraction_by_pdf\"], indent=2, default=lambda x: x.__dict__, ensure_ascii=False))\n",
    "\n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(\"\\n[최종 생성된 분석 보고서]\")\n",
    "    print(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9a141c68",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2026-04-07 22:48:07,160 [INFO] kakaocorp/kanana-1.5-2.1b-instruct-2505 로딩 중... device=cpu\n",
      "2026-04-07 22:48:09,034 [INFO] PDF 자동 분리를 시작합니다...\n",
      "2026-04-07 22:48:09,049 [INFO] 문서 스캔 중... (총 189페이지)\n",
      "2026-04-07 22:48:09,773 [INFO] (별도)포괄손익계산서 페이지 발견: 98\n",
      "2026-04-07 22:48:10,331 [INFO] 필터링 완료: [98, 99]\n",
      "2026-04-07 23:38:08,903 [INFO] \n",
      "[TableExtractor 원본 응답]\n",
      " {\n",
      "  \"unit_raw\": \"원\",\n",
      "  \"now_period\": \"2025.09.30\",\n",
      "  \"ref_period\": \"2024.09.30\",\n",
      "  \"now_period_key\": \"2025Q3\",\n",
      "  \"ref_period_key\": \"2024Q3\",\n",
      "  \"items\": {\n",
      "    \"2025Q3\": {\n",
      "      \"영업이익(손실)\": \"640,113,803\",\n",
      "      \"금융수익\": \"115,852,452\",\n",
      "      \"금융비용\": \"(76,668,238)\",\n",
      "      \"기타수익\": \"2,134,763\",\n",
      "      \"기타비용\": \"0\",\n",
      "      \"법인세비용차감전순이익(손실)\": \"834,769,256\",\n",
      "      \"법인세비용(수익)\": \"23,555,974\",\n",
      "      \"당기순이익(손실)\": \"811,213,282\",\n",
      "      \"기타포괄손익\": \"(11,582,150)\",\n",
      "      \"후속적으로 당기손익으로 재분류되지 않는 항목\": \"(11,582,150)\",\n",
      "      \"확정급여제도의 재측정손익\": \"(11,582,150)\",\n",
      "      \"세후기타포괄손익, 지분상품에 대한 투자자산\": \"0\",\n",
      "      \"총포괄손익\": \"799,631,132\"\n",
      "    },\n",
      "    \"2024Q3\": {\n",
      "      \"영업이익(손실)\": \"1,028,285,545\",\n",
      "      \"금융수익\": \"(12,235,094)\",\n",
      "      \"금융비용\": \"130,770,047\",\n",
      "      \"기타수익\": \"144,955,909\",\n",
      "      \"기타비용\": \"66,174,644\",\n",
      "      \"법인세비용차감전순이익(손실)\": \"964,061,669\",\n",
      "      \"법인세비용(수익)\": \"21,051,790\",\n",
      "      \"당기순이익(손실)\": \"943,009,879\",\n",
      "      \"기타포괄손익\": \"(6,849,775)\",\n",
      "      \"후속적으로 당기손익으로 재분류되지 않는 항 목\": \"(6,849,775)\",\n",
      "      \"확정급여제도의 재측정손익\": \"(6,849,775)\",\n",
      "      \"세후기타포괄손익, 지분상품에 대한 투자자산\": \"0\",\n",
      "      \"총포괄손익\": \"936,160,104\"\n",
      "    }\n",
      "  }\n",
      "} \n",
      "==================================================\n",
      "2026-04-07 23:39:23,911 [INFO] \n",
      "[LLM 추출 Raw Data]\n",
      "2026-04-07 23:39:23,911 [INFO] {\n",
      "  \"./temp_sliced_finance.pdf\": {\n",
      "    \"unit_raw\": \"원\",\n",
      "    \"now_period\": \"2025.09.30\",\n",
      "    \"ref_period\": \"2024.09.30\",\n",
      "    \"now_period_key\": \"2025Q3\",\n",
      "    \"ref_period_key\": \"2024Q3\",\n",
      "    \"items\": {\n",
      "      \"2025Q3\": {\n",
      "        \"영업이익(손실)\": \"640,113,803\",\n",
      "        \"금융수익\": \"115,852,452\",\n",
      "        \"금융비용\": \"(76,668,238)\",\n",
      "        \"기타수익\": \"2,134,763\",\n",
      "        \"기타비용\": \"0\",\n",
      "        \"법인세비용차감전순이익(손실)\": \"834,769,256\",\n",
      "        \"법인세비용(수익)\": \"23,555,974\",\n",
      "        \"당기순이익(손실)\": \"811,213,282\",\n",
      "        \"기타포괄손익\": \"(11,582,150)\",\n",
      "        \"후속적으로 당기손익으로 재분류되지 않는 항목\": \"(11,582,150)\",\n",
      "        \"확정급여제도의 재측정손익\": \"(11,582,150)\",\n",
      "        \"세후기타포괄손익, 지분상품에 대한 투자자산\": \"0\",\n",
      "        \"총포괄손익\": \"799,631,132\"\n",
      "      },\n",
      "      \"2024Q3\": {\n",
      "        \"영업이익(손실)\": \"1,028,285,545\",\n",
      "        \"금융수익\": \"(12,235,094)\",\n",
      "        \"금융비용\": \"130,770,047\",\n",
      "        \"기타수익\": \"144,955,909\",\n",
      "        \"기타비용\": \"66,174,644\",\n",
      "        \"법인세비용차감전순이익(손실)\": \"964,061,669\",\n",
      "        \"법인세비용(수익)\": \"21,051,790\",\n",
      "        \"당기순이익(손실)\": \"943,009,879\",\n",
      "        \"기타포괄손익\": \"(6,849,775)\",\n",
      "        \"후속적으로 당기손익으로 재분류되지 않는 항 목\": \"(6,849,775)\",\n",
      "        \"확정급여제도의 재측정손익\": \"(6,849,775)\",\n",
      "        \"세후기타포괄손익, 지분상품에 대한 투자자산\": \"0\",\n",
      "        \"총포괄손익\": \"936,160,104\"\n",
      "      }\n",
      "    }\n",
      "  }\n",
      "}\n",
      "2026-04-07 23:39:23,911 [INFO] \n",
      "============================================================\n",
      "2026-04-07 23:39:23,912 [INFO] \n",
      "[최종 생성된 분석 보고서]\n",
      "2026-04-07 23:39:23,912 [INFO] [단위]: 백만원, [비교]: YoY\n",
      "[선택된 지표] 영업이익(손실), 법인세비용차감전순이익(손실), 법인세비용(수익), 당기순이익(손실), 영업수익\n",
      "\n",
      "1) 핵심 지표 변동 (Top Moves)\n",
      "- 영업이익(손실): Δ -388 (-37.7%)\n",
      "- 당기순이익(손실): Δ -132 (-14.0%)\n",
      "- 법인세비용차감전순이익(손실): Δ -129 (-13.4%)\n",
      "- 법인세비용(수익): Δ 3 (11.9%)\n",
      "\n",
      "2) 분석 요약\n",
      "- 총평: 최근 몇 개 분기의 실적에서 전반적으로 적자 또는 악화 경향이 확인되며, 수익성 지표들이 하락하고 있습니다. 특히 영업이익과 당기순이익, 법인세비용차감전순이익 등 주요 손익 계정에서 부진한 성과가 나타나고 있어, 사업 환경 변화 및 비효율적인 운영 가능성을 배제할 수 없습니다. 장기적인 관점에서 원인 파악과 구조적 개선 방안 마련이 필요합니다.\n",
      "\n",
      "[핵심 지표 변화 요약 표]\n",
      "| 지표 | 2024Q3 (백만원) | 2025Q3 (백만원) | 변동액 (백만원) | 증감률 (%) |\n",
      "|---|---|---|---|---|\n",
      "| 영업이익(손실) | 1,028.29 | 640.11 | -388.17 | -37.7% |\n",
      "| 당기순이익(손실) | 943.01 | 811.21 | -131.80 | -14.0% |\n",
      "| 법인세비용차감전순이익(손실) | 964.06 | 834.77 | -129.29 | -13.4% |\n",
      "| 법인세비용(수익) | 21.05 | 23.56 | 2.50 | 11.9% |\n",
      "\n",
      "  • 영업이익: 최근 분기별로 감소 추세이며, 연간 기준으로도 전년 대비 큰 폭의 하락이 발생했습니다. 이는 주력 제품 판매량 감소, 원가 상승, 매출 구조의 불균형 등 다양한 내부 요인이 복합적으로 작용했을 것으로 판단됩니다. 향후 시장 동향과 경쟁사 대응 전략, 비용 효율화 노력이 중요합니다.\n",
      "  • 당기순이익: 순이익 역시 유사하게 감소하였으며, 세금 부담 증가에도 불구하고 이익 규모 자체가 축소되고 있습니다. 외부 환경 변화, 원가 상승 압박, 수익성 저하가 누적된 결과로 보입니다. 지속 가능한 수익 창출 기반 강화가 시급합니다.\n",
      "  • 법인세비용차감전순이익: 해당 항목에서도 적자 기조가 이어지고 있으며, 세금 부담 완화 효과가 미미한 상황입니다. 비용 구조 최적화와 함께 수익성 회복이 필수적입니다.\n",
      "  • 법인세비용: 법인세비용은 소폭 증가했으나, 전체적인 손익 구조상 긍정적인 신호로 해석하기 어렵습니다. 세법 변경이나 과세 정책 영향일 수도 있지만, 장기적으로는 수익성 개선을 통한 세부담 완화가 바람직합니다.\n",
      "- 특이사항/주의:\n",
      "  • 연속적인 손익 악화 현상은 경영진의 전략적 의사결정이 충분히 검토되지 않았거나, 내부 운영 시스템의 비효율성이 여전히 존재함을 의미합니다. 특히 영업이익, 당기순이익, 법인세비용차감전순이익 등 핵심 손익 계정의 지속적인 적자 국면은 추가적인 원인 진단과 구체적인 개선 로드맵 마련이 요구됩니다. 또한, 법인세비용의 일시적 증가는 세법상의 영향일 가능성이 높으므로, 장기적으로는 수익성 제고를 통해 세부담을 줄이는 것이 합리적입니다.\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    #upstage = UpstageDocumentParseClient()\n",
    "    #llm = LLMClient(model_id=\"kakaocorp/kanana-1.5-2.1b-instruct-2505\")\n",
    "    # 파일 경로 설정 \n",
    "    original_pdf = \"./[폴라리스오피스]분기보고서(2025.11.14).pdf\"\n",
    "    sliced_pdf = \"./temp_sliced_finance.pdf\" # 잘라낸 파일 임시 저장\n",
    "\n",
    "    # 자동 스캔 및 자르기 실행\n",
    "    print(f\"{original_pdf}분석\\n\")\n",
    "    print(\"PDF 자동 분리를 시작합니다...\")\n",
    "    auto_slice_financials(original_pdf, sliced_pdf)\n",
    "\n",
    "    # 파이프라인 실행 \n",
    "    report_state, text = run_pipeline(\n",
    "        pdf_paths=[sliced_pdf], # 자른 파일을 투입\n",
    "        llm=llm,\n",
    "        upstage=upstage,\n",
    "        compare=\"YoY\",\n",
    "        top_k=5,\n",
    "        use_reasoning=True\n",
    "    )\n",
    "\n",
    "    # 결과 출력\n",
    "    print(\"\\n[LLM 추출 Raw Data]\")\n",
    "    print(json.dumps(report_state[\"llm_extraction_by_pdf\"], indent=2, default=lambda x: x.__dict__, ensure_ascii=False))\n",
    "\n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(\"\\n[최종 생성된 분석 보고서]\")\n",
    "    print(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "40e4a283",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2026-04-08 14:06:22,987 [INFO] PDF 자동 분리를 시작합니다...\n",
      "2026-04-08 14:06:23,007 [INFO] 문서 스캔 중... (총 228페이지)\n",
      "2026-04-08 14:06:23,995 [INFO] (별도)포괄손익계산서 페이지 발견: 118\n",
      "2026-04-08 14:06:24,055 [INFO] (별도)포괄손익계산서 페이지 발견: 126\n",
      "2026-04-08 14:06:24,742 [INFO] 필터링 완료: [118, 119]\n",
      "2026-04-08 14:22:04,728 [INFO] \n",
      "[LLM 추출 Raw Data]\n",
      "2026-04-08 14:22:04,733 [INFO] {\n",
      "  \"./temp_sliced_finance.pdf\": {\n",
      "    \"unit_raw\": \"백만원\",\n",
      "    \"now_period\": \"2025.03.31\",\n",
      "    \"ref_period\": \"2024.03.31\",\n",
      "    \"now_period_key\": \"2025Q1\",\n",
      "    \"ref_period_key\": \"2024Q1\",\n",
      "    \"items\": {\n",
      "      \"2025Q1\": {\n",
      "        \"영업이익\": \"199,032\",\n",
      "        \"법인세비용차감전순이익\": \"264,441\",\n",
      "        \"법인세비용\": \"(56,808)\",\n",
      "        \"당기순이익\": \"207,633\",\n",
      "        \"매출액\": \"917,225\"\n",
      "      },\n",
      "      \"2024Q1\": {\n",
      "        \"영업이익\": \"208,656\",\n",
      "        \"법인세비용차감전순이익\": \"345,297\",\n",
      "        \"법인세비용\": \"(67,154)\",\n",
      "        \"당기순이익\": \"278,143\",\n",
      "        \"매출액\": \"791,799\"\n",
      "      }\n",
      "    }\n",
      "  }\n",
      "}\n",
      "2026-04-08 14:22:04,733 [INFO] \n",
      "============================================================\n",
      "2026-04-08 14:22:04,734 [INFO] \n",
      "[최종 생성된 분석 보고서]\n",
      "2026-04-08 14:22:04,734 [INFO] [단위]: 백만원, [비교]: YoY\n",
      "[선택된 지표] 영업이익, 법인세비용차감전순이익, 법인세비용, 당기순이익, 매출액\n",
      "\n",
      "1) 핵심 지표 변동 (Top Moves)\n",
      "- 당기순이익: Δ -70,510 (-25.4%)\n",
      "- 법인세비용차감전순이익: Δ -80,856 (-23.4%)\n",
      "- 매출액: Δ 125,426 (15.8%)\n",
      "- 법인세비용: Δ 10,346 (-15.4%)\n",
      "- 영업이익: Δ -9,624 (-4.6%)\n",
      "\n",
      "2) 분석 요약\n",
      "- 총평: 최근 몇 개 분기의 실적에서 매출액과 법인세비용 등 일부 수치가 성장 또는 개선되는 모습을 보이고 있으나, 당기순이익과 법인세비용차감전순이익 등 주요 손익지표에서는 적자 폭이 확대되고 있어 전반적으로 이익 창출 능력이 약화될 가능성을 시사합니다. 이는 비용 구조의 효율화나 수익성 개선 노력이 필요함을 의미하며, 장기적인 관점에서 경쟁력 유지를 위해 추가적인 원가절감 및 수익성 제고 전략이 요구됩니다.\n",
      "\n",
      "[핵심 지표 변화 요약 표]\n",
      "| 지표 | 2024Q1 (백만원) | 2025Q1 (백만원) | 변동액 (백만원) | 증감률 (%) |\n",
      "|---|---|---|---|---|\n",
      "| 당기순이익 | 278,143.00 | 207,633.00 | -70,510.00 | -25.4% |\n",
      "| 법인세비용차감전순이익 | 345,297.00 | 264,441.00 | -80,856.00 | -23.4% |\n",
      "| 매출액 | 791,799.00 | 917,225.00 | 125,426.00 | 15.8% |\n",
      "| 법인세비용 | -67,154.00 | -56,808.00 | 10,346.00 | -15.4% |\n",
      "| 영업이익 | 208,656.00 | 199,032.00 | -9,624.00 | -4.6% |\n",
      "\n",
      "  • 당기순이익: 최근 연도 대비 순이익이 크게 감소하였으며, 이는 주로 영업이익의 축소와 함께 비용 증가 혹은 세금 부담 증가 등 여러 요인에 기인한 것으로 판단됩니다. 향후에는 수익성 개선을 위한 내부 구조조정과 비용 최적화가 중요하다고 사료됩니다.\n",
      "  • 법인세비용차감전순이익: 법인세비용 차감 전 순이익 역시 큰 폭으로 하락했으며, 이는 영업이익의 감소와 직접적으로 연결되어 있습니다. 앞으로는 영업이익 개선을 통한 이익률 회복이 핵심 과제입니다.\n",
      "  • 매출액: 매출액은 꾸준히 증가하는 추세이며, 시장 환경 변화에 긍정적으로 대응하고 있는 것으로 평가됩니다. 다만, 매출 증대가 실제 이익으로 이어질 수 있도록 영업이익률 개선에도 힘써야 할 것입니다.\n",
      "  • 법인세비용: 법인세비용은 소폭 감소하였으나, 여전히 전체 비용 구조에서 상당 부분을 차지하고 있어, 세법 변경이나 세무전략의 효과가 있었던 것으로 보입니다. 그러나 세금 부담 완화를 위해서는 비용 구조의 합리화가 병행되어야 합니다.\n",
      "  • 영업이익: 영업이익은 소폭 감소하였으며, 이는 주로 원가상승이나 판매관리비 등의 증가 때문일 가능성이 높습니다. 단기적으로는 일시적 요인이 있을 수 있지만, 장기적으로는 수익구조 개선이 필수적입니다.\n",
      "\n",
      "- 특이사항/주의:\n",
      "  • 매출액은 꾸준히 증가하고 있으나, 이에 상응하는 영업이익의 개선이 미흡하여 이익창출능력이 저하되고 있습니다. 특히 당기순이익과 법인세비용차감전순이익의 적자 폭 확대는 비용 구조의 문제와 세무환경 악화 등 복합적인 요인에 의해 발생한 것으로 판단되며, 이를 해결하기 위해서는 원가절감, 수익성 중심의 사업 운영, 그리고 세무전략의 재검토가 필요합니다. 또한, 단기간 내에 급격한 이익 개선을 기대하기보다는 중장기적인 체질 강화 전략이 요구됩니다.\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    #upstage = UpstageDocumentParseClient()\n",
    "    #llm = LLMClient(model_id=\"kakaocorp/kanana-1.5-2.1b-instruct-2505\")\n",
    "    # 파일 경로 설정 \n",
    "    original_pdf = \"./[케이티앤지]분기보고서(2025.05.15).pdf\"\n",
    "    sliced_pdf = \"./temp_sliced_finance.pdf\" # 잘라낸 파일 임시 저장\n",
    "\n",
    "    # 자동 스캔 및 자르기 실행\n",
    "    print(\"PDF 자동 분리를 시작합니다...\")\n",
    "    auto_slice_financials(original_pdf, sliced_pdf)\n",
    "\n",
    "    # 파이프라인 실행 \n",
    "    report_state, text = run_pipeline(\n",
    "        pdf_paths=[sliced_pdf], # 자른 파일을 투입\n",
    "        llm=llm,\n",
    "        upstage=upstage,\n",
    "        compare=\"YoY\",\n",
    "        top_k=5,\n",
    "        use_reasoning=True\n",
    "    )\n",
    "\n",
    "    # 결과 출력\n",
    "    print(\"\\n[LLM 추출 Raw Data]\")\n",
    "    print(json.dumps(report_state[\"llm_extraction_by_pdf\"], indent=2, default=lambda x: x.__dict__, ensure_ascii=False))\n",
    "\n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(\"\\n[최종 생성된 분석 보고서]\")\n",
    "    print(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "65bc4ba1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2026-04-08 14:41:17,682 [INFO] PDF 자동 분리를 시작합니다...\n",
      "2026-04-08 14:41:17,696 [INFO] 문서 스캔 중... (총 191페이지)\n",
      "2026-04-08 14:41:18,580 [INFO] (별도)포괄손익계산서 페이지 발견: 103\n",
      "2026-04-08 14:41:19,171 [INFO] 필터링 완료: [103, 104]\n",
      "2026-04-08 14:54:30,450 [INFO] \n",
      "[LLM 추출 Raw Data]\n",
      "2026-04-08 14:54:30,452 [INFO] {\n",
      "  \"./temp_sliced_finance.pdf\": {\n",
      "    \"unit_raw\": \"천원\",\n",
      "    \"now_period\": \"2025.09.30\",\n",
      "    \"ref_period\": \"2024.09.30\",\n",
      "    \"now_period_key\": \"2025Q3\",\n",
      "    \"ref_period_key\": \"2024Q3\",\n",
      "    \"items\": {\n",
      "      \"2025Q3\": {\n",
      "        \"매출액\": \"298,290,953\",\n",
      "        \"매출총이익\": \"67,679,800\",\n",
      "        \"영업이익\": \"10,806,349\",\n",
      "        \"법인세비용차감전순이익\": \"37,257,902\",\n",
      "        \"분기순손익\": \"31,824,383\"\n",
      "      },\n",
      "      \"2024Q3\": {\n",
      "        \"매출액\": \"126,392,630\",\n",
      "        \"매출총이익\": \"54,356,145\",\n",
      "        \"영업이익\": \"5,148,924\",\n",
      "        \"법인세비용차감전순이익\": \"(35,006,134)\",\n",
      "        \"분기순손익\": \"(18,292,601)\"\n",
      "      }\n",
      "    }\n",
      "  }\n",
      "}\n",
      "2026-04-08 14:54:30,452 [INFO] \n",
      "============================================================\n",
      "2026-04-08 14:54:30,453 [INFO] \n",
      "[최종 생성된 분석 보고서]\n",
      "2026-04-08 14:54:30,453 [INFO] [단위]: 백만원, [비교]: YoY\n",
      "[선택된 지표] 매출액, 매출총이익, 영업이익, 법인세비용차감전순이익, 분기순손익\n",
      "\n",
      "1) 핵심 지표 변동 (Top Moves)\n",
      "- 분기순손익: Δ 50,117 (-274.0%)\n",
      "- 법인세비용차감전순이익: Δ 72,264 (-206.4%)\n",
      "- 매출액: Δ 171,898 (136.0%)\n",
      "- 영업이익: Δ 5,657 (109.9%)\n",
      "- 매출총이익: Δ 13,324 (24.5%)\n",
      "\n",
      "2) 분석 요약\n",
      "- 총평: 최근 분기 실적에서 흑자전환이 확인되었으며, 전반적으로 매출과 이익이 크게 성장한 것으로 나타납니다. 특히 영업이익과 매출총이익이 큰 폭으로 개선되어 수익성이 전반적으로 향상되고 있음을 알 수 있습니다. 다만, 법인세비용차감전순이익 역시 흑자전환하였으나, 여전히 적자가 이어졌던 순손익 부분의 회복이 주목됩니다. 앞으로도 이러한 흐름이 유지된다면 장기적인 성장 기반을 확보할 것으로 기대되나, 세부 원인 및 추가적인 비용 구조 개선 등이 필요할 것으로 판단됩니다.\n",
      "\n",
      "[핵심 지표 변화 요약 표]\n",
      "| 지표 | 2024Q3 (백만원) | 2025Q3 (백만원) | 변동액 (백만원) | 증감률 (%) |\n",
      "|---|---|---|---|---|\n",
      "| 분기순손익 | -18,292.60 | 31,824.38 | 50,116.98 | -274.0% |\n",
      "| 법인세비용차감전순이익 | -35,006.13 | 37,257.90 | 72,264.04 | -206.4% |\n",
      "| 매출액 | 126,392.63 | 298,290.95 | 171,898.32 | 136.0% |\n",
      "| 영업이익 | 5,148.92 | 10,806.35 | 5,657.43 | 109.9% |\n",
      "| 매출총이익 | 54,356.15 | 67,679.80 | 13,323.65 | 24.5% |\n",
      "\n",
      "  • 분기순손익: 흑자전환, 손실폭 축소 및 흑자 전환은 긍정적 신호이며, 순손익 개선이 전체 실적 개선의 중요한 계기가 될 것으로 보입니다.\n",
      "  • 법인세비용차감전순이익: 흑자전환, 순손익 개선이 법인세 부담 완화에도 긍정적으로 작용할 것으로 예상됩니다.\n",
      "  • 매출액: 성장/개선, 시장 경쟁력 강화 또는 가격 인상 등 외부 환경 변화에 효과적으로 대응한 결과로 해석됩니다.\n",
      "  • 영업이익: 성장/개선, 수익구조 개선 및 효율적인 운영이 실질적인 이익 증가의 주요 원인으로 분석됩니다.\n",
      "  • 매출총이익: 성장/개선, 원가절감 및 판매관리비 감축 등이 매출총이익률 상승의 핵심 요인으로 평가됩니다.\n",
      "\n",
      "- 특이사항/주의:\n",
      "  • 법인세비용차감전순이익의 흑자전환은 세금 부담 완화 측면에서 긍정적이나, 순손익의 지속적인 개선이 필요합니다. 또한, 매출총이익률 상승이 일회성 요인이 아닌 지속 가능한 구조로 자리 잡아야 하며, 영업이익마진 확대를 위한 비용 관리가 중요합니다. 순손익 개선을 위해 원가절감, 비효율적 사업 정리, 신규사업 진출 등 다양한 전략적 대응이 필요하다고 판단됩니다.\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    #upstage = UpstageDocumentParseClient()\n",
    "    #llm = LLMClient(model_id=\"kakaocorp/kanana-1.5-2.1b-instruct-2505\")\n",
    "    # 파일 경로 설정 \n",
    "    original_pdf = \"./[하이브][정정]분기보고서(2026.01.07).pdf\"\n",
    "    sliced_pdf = \"./temp_sliced_finance.pdf\" # 잘라낸 파일 임시 저장\n",
    "\n",
    "    # 자동 스캔 및 자르기 실행\n",
    "    print(\"PDF 자동 분리를 시작합니다...\")\n",
    "    auto_slice_financials(original_pdf, sliced_pdf)\n",
    "\n",
    "    # 파이프라인 실행 \n",
    "    report_state, text = run_pipeline(\n",
    "        pdf_paths=[sliced_pdf], # 자른 파일을 투입\n",
    "        llm=llm,\n",
    "        upstage=upstage,\n",
    "        compare=\"YoY\",\n",
    "        top_k=5,\n",
    "        use_reasoning=True\n",
    "    )\n",
    "\n",
    "    # 결과 출력\n",
    "    print(\"\\n[LLM 추출 Raw Data]\")\n",
    "    print(json.dumps(report_state[\"llm_extraction_by_pdf\"], indent=2, default=lambda x: x.__dict__, ensure_ascii=False))\n",
    "\n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(\"\\n[최종 생성된 분석 보고서]\")\n",
    "    print(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b7438bc9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
